language: cpp
compiler:
  - gcc
  - clang
before_script: sudo ./pre-configure.sh && .travis/configure.sh
script: .travis/make.sh
branches:
  only:
    - master
notifications:
  recipients:
    - axr-ci@googlegroups.com
  email:
    on_success: change
    on_failure: always
  irc: "irc.freenode.net#axr"
